name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - master
trigger:
  branches:
    include:
      - master

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-nice-sand-0f0533103-variable-group
  steps:
  - checkout: self
    submodules: true

  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_SAND_0F0533103)
      app_location: "/"          # where package.json and index.html live
      api_location: ""           # (optional)
      output_location: "dist"    # Vite build output
      # DO NOT skip the app build here
